/* eslint-disable @next/next/no-sync-scripts */
import Navbar from "@/components/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import Alert from "@/components/Alert";
import NavBar2 from "@/components/NavBar2";
import { ThemeProvider } from "../components/hooks/ThemeContext";
import Footer from "@/components/Footer";
import LoadingBar from 'react-top-loading-bar'
import { useEffect, useState } from 'react';
// import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.min";
import { useRouter } from "next/router";

function MyApp({ Component, pageProps }) {

  const [progress, setProgress] = useState(0)
  const router = useRouter()

  useEffect(() => {
    router.events.on('routeChangeStart', () => {
      setProgress(0);
    });

    router.events.on('routeChangeComplete', () => {
      setProgress(100);
    });

    router.events.on('routeChangeError', () => {
      setProgress(100);
    });
  }, [router.events]);

  return (
    <>
    <LoadingBar
        color='#f11946'
        progress={progress}
        waitingTime={400}
        onLoaderFinished={() => setProgress(0)}
      />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        
      </Head>
      <ThemeProvider>
        <Navbar />
        <Alert alert="This is Beta version💫" />
        <NavBar2 />
        <Component {...pageProps} />
        <Footer />
      </ThemeProvider>
    </>
  );
}

export default MyApp;
